version: "3.9"

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nodeapp:
    build: .
    restart: unless-stopped
    container_name: nodeapp
    depends_on:
      - mongodb
    ports:
      - "3030:3030"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/dealershipsdb

volumes:
  mongo_data:
