name: Lint Code

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint_js:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint
        run: |
          echo "Running JS lint..."
           jshint --exclude-path .jshintignore .
